# ANSIBLE globals #

ansible_connection: local

# ENV-specific vars #

env: "dev"

# Roles globals #

region: "us-west-2"

# (THIS) eks_cluster_name: this will be the exact cluster name
# (AUTO) eks_cluster_stack_name: generated CF name "eksctl-{{ eks_cluster_name }}-cluster"
# (AUTO) eks_nodegroup_stack_name: generated CF name "eksctl-{{ eks_cluster_name }}-nodegroup-{{ worker-nodes-name }}"

eks_cluster_name: "capstone-{{ env }}"

# name of our aws CF stack:
cf_stack_name: "eksctl-{{ eks_cluster_name }}-stack"

# ROLES specific #

# CF ROLE:
vpc_cidr_block: "10.0.0.0/16"

# EKSCTL ROLE:
worker_frontend_name: 'frontend'
worker_frontend_instance_type: 't2.medium'
worker_frontend_desired_capacity: 1
worker_frontend_volume_size: 10
worker_frontend_ssh_key_name: 'capstone-nodes'

worker_backend_name: 'backend'
worker_backend_instance_type: 't2.medium'
worker_backend_desired_capacity: 1
worker_backend_volume_size: 10